#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#
export TERM="xterm-256color"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
eval `dircolors ~/.dir_colors`

alias vi="nvim"
alias vim="nvim"

# ruby
# eval "$(rbenv init -)"
# python
#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

case `uname` in
  Darwin)
    # commands for OS X go here
    echo "macos"
    . /usr/local/opt/asdf/asdf.sh
    . /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash
  ;;
  Linux)
    # commands for Linux go here
    echo "linux"
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    . /home/linuxbrew/.linuxbrew/opt/asdf/asdf.sh
  ;;
  FreeBSD)
    # commands for FreeBSD go here
  ;;
esac
